### ISSUE TITLE
Fishing job

### ISSUE THREAD

**Issue by AsmoEum** [Smolwong/Smolcraft#3] opened 2024-07-23 02:29 UTC
Cod = $2.29 1.94xp
Tropical Fish = $2.29 1.94xp
![image](https://github.com/user-attachments/assets/bc04633b-12a5-4e11-a6d2-166e0d60511f)

**Comment by Smolwong** [comment] 2024-07-24 10:13
Works as intended.

**Comment by Smolwong** [comment] 2024-07-24 10:35
Changing close type

**Comment by Smolwong** [comment] 2024-07-24 10:36
Closed as Not Planned

**Closed by Smolwong** 2024-07-24 10:36 UTC
Labels: wontfix
